require:
  - rubocop-rails

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

# Style/CommentedKeyword:
#      Exclude:
#     - 'spec/**/*'

Lint/UselessAssignment:
  Exclude:
    - 'spec/**/*'

RSpec/LetSetup:
  Exclude:
    - 'spec/**/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/**/*'

AllCops:
  TargetRubyVersion: 2.7
