require:
  - rubocop-rails

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

RSpec/LetSetup:
   Exclude:
    - 'spec/**/*'

RSpec/Focus:
   Exclude:
    - 'spec/**/*'

Layout/IndentationConsistency:
   Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
   Exclude:
    - 'spec/**/*'

Lint/UselessAssignment:
   Exclude:
    - 'spec/**/*'


RSpec/AnyInstance:
   Exclude:
    - 'spec/**/*'

Style/CommentedKeyword:
   Exclude:
    - 'spec/**/*'

AllCops:
  TargetRubyVersion: 2.7

RSpec/MultipleExpectations:
   Exclude:
    - 'spec/**/*'
